### ISSUE TITLE
Error: "Could not resolve host: test.txt" while uploading object to a bucket

### ISSUE THREAD

**Issue by alexthomas112** [opensds/multi-cloud#65]
I have my test.txt file created in path "/root/gopath/src/github.com/opensds/multi-cloud". When I run _curl -H "Content-type: application/xml" -X -T "test.txt" PUT http://127.0.0.1:8089/v1/s3/bucket009/test.txt_ I get issue as **Could not resolve host: test.txt** **405: Method Not Allowed**

Please help me with this error.
Screenshot of the same is attached
![capture1](https://user-images.githubusercontent.com/45204895/48780643-654b0b80-ed00-11e8-9867-bce3d42e8e0e.PNG)
Thanks!

**Comment by wisererik** [comment]
@alexthomas112  thanks, we will test and resolve it

**Comment by liuqinguestc** [comment]
@alexthomas112  thank you for your question, the problem is that you use the wrong curl command, the correct  command is 'curl -H "Content-type: application/xml" -T test.txt -X PUT 
 http://127.0.0.1:8089/v1/s3/bucket_azure1/test.txt' ,X and PUT should be together
![image](https://user-images.githubusercontent.com/29296663/48878935-a77d6580-ee44-11e8-8fcb-bdc133179e45.png)
